//require('jquery');
require('script!./bower_components/jquery/dist/jquery.js');
require('./js/src/test.jsx');
require('./js/src/sign-up.jsx');
require('script!./js/src/mailchimp.js');
require('script!./bower_components/jquery-colorbox/jquery.colorbox.js');
//require('imports?jQuery=jquery,$=jquery,this=>window!jquery-colorbox/jquery.colorbox.js')
//require('imports?jQuery=jquery,$=jquery,this=>window!jquery.knob.js')
//require('imports?jQuery=jquery,$=jquery,this=>window!jquery.throttle.js')
require('script!./assets/slick-circular/js/jquery.knob.js');
require('script!./assets/slick-circular/js/jquery.throttle.js');
require('script!./assets/slick-circular/js/jquery.classycountdown.js');
//require('script!./js/src/height.js');
require('script!./js/src/menu.js');
require('script!./js/src/dynamic-height.js');
require('script!./js/src/scroll.js');
//require('imports?jQuery=jquery,$=jquery,this=>window!scroll.js')
require('script!./js/src/mobile-menu.js');
require('script!./js/src/colorbox.js');
require('script!./js/src/modal.js');
require('script!./js/src/countdown.js');
